---
title: "final Exam"
author: "karthikeyan ramesh"
date: "2022-13-11"
output:
  pdf_document: default
  word_document: default
---

```{r}

#I assumed that groups were assembling for a class for the objectives of this project.According to my analysis, the following elements are crucial to the group's success: students current gpa, relevancy of academic activity, and a students participation. 

#The total score based on all three criteria. Here, dividing the GPA by four would standardise the GPA, while dividing by ten would normalize the activity. Then, a weighted average would be calculated, with weights assigned in accordance with their significance to success. GPA weighs.5, activity weighs.25, and involvement weighs.25. The data frame in use is displayed below.

library(dplyr)
NR_DATA <- data.frame("Student_Name" = c(1:12), "GPA" = c(3.4, 3.7,3.5, 3.1, 3.1, 2.3, 3 , 3.2, 3.4, 3.5, 2.7 , 2.4), "Participation" = c(.5,.5,.15,.15,.35,.5,.5,.35,.35,.35,.35,.15), "activity" = c(10,5,10,5,10,6,7,7,6,5,9,10))
NR_DATA_Coeff <- mutate(NR_DATA, "coeff" = (((GPA/4)*.5) + ((activity/10)*.25) + (Participation *.25)))
View(NR_DATA_Coeff)
```

```{r}
#In order for the execution of the problem to make sense, restrictions on group size (three students per group) and students only being allocated to one team are necessary. Additional restrictions were applied in an effort to increase each team's chances of victory.

#participation - In order to ensure that each group has high level of participation, a constraint was added that each team must have a sum total of 21 of their participation score. (70% of the maximum value of 30 per team, or an average of 7)


getwd()


library(lpSolveAPI)
NR <- read.lp("C:/Users/ASUS/Downloads/qmm-final.lp")
NR
solve(NR)
get.objective(NR)
get.variables(NR)
get.constraints(NR)

#Optimal Groups based on output below:
#Group1:Student 1, Student 4, Student 6
#Group2:Student 3, Student 9, Student 12
#Group3:Student 2, Student 7, Student 11
#Group4:Student 5, Student 8, Student 10
```

\`\`\`
